### ISSUE TITLE
How to render hash

### ISSUE THREAD

**Issue by sudeeptarlekar** [jsonapi-rb/jsonapi-rails#107]
So I have this basic configuration hash as follows

```
{
  footer_text: 'CopyRight',
  footer_color: '#FFF',
  footer_logo: '#s3_image_path'
}
```

Now I want to send this hash as a json using JSONAPI. But every time I am getting error while rendering this. Tried with adding a serializer also but that didn't worked. [Here](https://gist.github.com/sudeeptarlekar/53a3ba0bc84b28730e31ebcdd58a7d36) is complete code.

What am I missing here or how can I render a hash using JSONAPI in rails?

Thanks in advance

**Comment by gmkohler** [comment]
@sudeeptarlekar you'll have more luck on the gitter https://gitter.im/jsonapi-rb/Lobby

**Comment by gmkohler** [comment]
The issue here is that unless otherwise specified, the library will look for a class named `SerializableClassName`, see the [default `class` configuration](https://github.com/jsonapi-rb/jsonapi-rails/blob/11b6fbe368e1bba59159920f62f7bc5d663de10c/lib/generators/jsonapi/initializer/templates/initializer.rb#L3-L7).

You could either make a `Configuration` class/struct to expose those attributes, or specify in the controller endpoint:

```ruby
render jsonapi: { ... }, class: { Hash: ConfigurationSerializer }
```

The latter approach will likely be more scalable

**Comment by sudeeptarlekar** [comment]
@gmkohler thanks for inputs but even passing Hash with class argument will result in 500 error as serialiser will look for `id`. So I ended up using dummy class and wrapped the config hash inside that dummy hash as shown below.

```
class ConfigurationsController < ApiController
  def index
      render jsonapi: OpenStruct.new(id: '', configuration: { 'footer-logo': '#FFF' }),
             class: { OpenStruct: ConfigurationResponseSerializer }
  end
end

class ConfigurationResponseSerializer < JSONAPI::Serializable::Resource
  type 'configuration'

  attributes :configuration
end
```

Also, found weird thing that when I use string keys for `class` option in controller while sending the json data, then it raises 500 error with `UndefinedSerializableClass` error. Example show below.

```
render jsonapi: OpenStruct.new(id: '', configuration: { 'footer-logo': '#FFF' }),
       class: { 'OpenStruct' => ConfigurationResponseSerializer }
```

Closing this issue as this is resolved.
