### ISSUE TITLE
Consider generating (de)serializable resources in `app/resources`.

### ISSUE THREAD

**Issue by beauby** [jsonapi-rb/jsonapi-rails#13]
# Current behavior
Generated (de)serializable resources are written to `app/serializable/` and `app/deserializable`.

# Suggested modification
Generated (de)serializable resources are written to `app/resources/`.

**Comment by richmolj** [comment]
Would the class name also change? `PostResource` instead of `SerializablePost`?

**Comment by beauby** [comment]
@richmolj The intent here was to have `app/resources/serializable_post.rb` and `app/resources/deserializable_post.rb`. I'm quite against merging the definition of the serialization and deserialization interfaces at the moment, though I'm up to discuss it.

**Comment by richmolj** [comment]
Ah, I see. I am planning on only using deserialization under-the-hood of [strong_resources](https://github.com/jsonapi-suite/strong_resources), so I would only ever have `app/resources/serializable_post`. Since that's actually a resource object, `PostResource` makes more sense for my particular use case. Not sure if that should be generalized or not atm.

**Comment by beauby** [comment]
As long as you name your class `PostResource` (for autoloading) and configure the inferrer accordingly, you're free to use any naming.

**Comment by beauby** [comment]
Closing this for now as generators are not a priority.
