### ISSUE TITLE
Do not attempt to deserialize requests with empty post data.

### ISSUE THREAD

**Issue by beauby** [jsonapi-rb/jsonapi-rails#20]
Only deserialize POST data if not `nil` and matches content-type.

**Comment by Startouf** [comment]
Just a note concerning content-type, 
I know it's silly, but I'm using Postman to build our API and so far Postman hasn't registered the `application/vnd.api+json` type and JSON syntax highlighting and linting only works for `application/json`, which is therefore the format I'm using on Postman to avoid wasting time because I had an extra comma...

I'd suggest to only print some sort of deprecation warning but still allow sending `application/json` content-type

**Comment by beauby** [comment]
@Startouf You can definitely override the content type – all the lib is doing is defaulting it to `application/vnd.api+json` in case it is not explicitly set. Did you encounter any issue?

**Comment by Startouf** [comment]
Hey, no issue here, systems working 100% 👍. 
I was just randomly looking at issues and when I saw this one, I understood in the future there might be some warning/error mechanism introduced if we didn't pass the jsonapi content-type `application/vnd.api+json`
