### ISSUE TITLE
Documentation (was: controller.params[:_jsonapi] is nil)

### ISSUE THREAD

**Issue by floriandejonckheere** [jsonapi-rb/jsonapi-rails#44]
Using the skeleton setup below, I am getting a NoMethodError in https://github.com/jsonapi-rb/jsonapi-rails/blob/master/lib/jsonapi/rails/controller.rb#L35 since `params[:_jsonapi]` seems to be nil. Am I missing something?

Test repository: https://github.com/floriandejonckheere/jsonapi-rails-bug

```
class UsersController < ApplicationController
  deserializable_resource :user, :only => %i[show]

  # GET /users/:id
  def show
    @user = User.find params[:id]

    render :jsonapi => @user
  end
end

```

```
class SerializableUser < JSONAPI::Serializable::Resource
  type 'users'

  attribute :name
end

```

**Comment by beauby** [comment]
Hi @floriandejonckheere – the call to `deserializable_resource` relies on the registered JSONAPI params parser (which puts the deserialized json under the `_jsonapi` key). Here since it's a `GET` action, the params parser won't kick in (nor should it). Just remove your `deserializable_resource` call and you should be set.

**Comment by floriandejonckheere** [comment]
All right, thanks! I didn't see any controller examples other than the `:create` method, so I assumed every call needed the `deserializable_resource`. Perhaps the documentation guide could benefit from a complete example application?

**Comment by beauby** [comment]
@floriandejonckheere Definitely – feel free to open a docs PR if you have a bit of spare time, otherwise I'll reopen this issue as a reminder to do it. Also, it would probably be good to fail with a clearer error message when this happens (something along the lines of "Could not deserialize resource foo because blah").

**Comment by floriandejonckheere** [comment]
I'm afraid I won't have any spare time the coming months, so I'll just reopen this issue.

**Comment by beauby** [comment]
Closing as #55 provides a log warning when this happens.
